modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="imperialcreatures"
version="1.0.0"
displayName="Imperial Creatures"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="alex, MCreator"

[[dependencies.imperialcreatures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



